import dotenv from "dotenv";
dotenv.config();
import mongoose from "mongoose";
import Event from "../models/eventModel.js";

async function seedEvents() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("MongoDB Connected");

    await Event.deleteMany({});
    console.log("Old events cleared");

    const organizerId = "692d475f914a10ef035bd294";

    const events = [
      {
        title: "Music Festival 2025",
        description: "A massive music festival featuring top artists.",
        image: "https://picsum.photos/300/200?music",
        category: "Music",
        location: {
          name: "Phoenix Arena",
          address: "Pune",
          location: { type: "Point", coordinates: [73.85, 18.52] },
        },
        startDate: new Date("2025-02-15T18:00:00Z"),
        endDate: new Date("2025-02-16T23:00:00Z"),
        price: 500,
        capacity: 5000,
        seatsAvailable: 5000,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Tech Innovation Summit",
        description: "A conference on AI, ML, Blockchain and Robotics.",
        image: "https://picsum.photos/300/200?tech",
        category: "Tech",
        location: {
          name: "Tech Park Hall",
          address: "Bengaluru",
          location: { type: "Point", coordinates: [77.59, 12.97] },
        },
        startDate: new Date("2025-03-05T10:00:00Z"),
        endDate: new Date("2025-03-07T17:00:00Z"),
        price: 1200,
        capacity: 800,
        seatsAvailable: 800,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Food Carnival 2025",
        description: "Taste cuisines from around the world.",
        image: "https://picsum.photos/300/200?food",
        category: "Food",
        location: {
          name: "City Mall Ground",
          address: "Mumbai",
          location: { type: "Point", coordinates: [72.835, 19.155] },
        },
        startDate: new Date("2025-04-02T10:00:00Z"),
        endDate: new Date("2025-04-04T22:00:00Z"),
        price: 250,
        capacity: 3000,
        seatsAvailable: 3000,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Startup Networking Night",
        description: "Meet founders, investors, and innovators.",
        image: "https://picsum.photos/300/200?business",
        category: "Business",
        location: {
          name: "Innovation Hub",
          address: "Hyderabad",
          location: { type: "Point", coordinates: [78.4867, 17.385] },
        },
        startDate: new Date("2025-05-10T19:00:00Z"),
        price: 0,
        capacity: 200,
        seatsAvailable: 200,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Yoga & Wellness Retreat",
        description: "A 2-day meditation and yoga wellness event.",
        image: "https://picsum.photos/300/200?wellness",
        category: "Health",
        location: {
          name: "Green Life Resort",
          address: "Rishikesh",
          location: { type: "Point", coordinates: [78.286, 30.086] },
        },
        startDate: new Date("2025-06-12T07:00:00Z"),
        endDate: new Date("2025-06-13T18:00:00Z"),
        price: 1500,
        capacity: 100,
        seatsAvailable: 100,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Photography Masterclass",
        description: "A hands-on workshop for beginner photographers.",
        image: "https://picsum.photos/300/200?camera",
        category: "Tech",
        location: {
          name: "Art Studio",
          address: "Delhi",
          location: { type: "Point", coordinates: [77.1025, 28.7041] },
        },
        startDate: new Date("2025-07-20T09:00:00Z"),
        price: 999,
        capacity: 60,
        seatsAvailable: 60,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Comedy Night",
        description: "Stand-up comedy show featuring top comedians.",
        image: "https://picsum.photos/300/200?comedy",
        category: "Music",
        location: {
          name: "Laugh Club Arena",
          address: "Ahmedabad",
          location: { type: "Point", coordinates: [72.571, 23.0225] },
        },
        startDate: new Date("2025-08-10T20:00:00Z"),
        price: 300,
        capacity: 400,
        seatsAvailable: 400,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Coding Bootcamp",
        description: "Learn Full Stack Development in 2 days.",
        image: "https://picsum.photos/300/200?code",
        category: "Tech",
        location: {
          name: "Code Academy",
          address: "Chennai",
          location: { type: "Point", coordinates: [80.27, 13.08] },
        },
        startDate: new Date("2025-09-01T09:00:00Z"),
        endDate: new Date("2025-09-02T18:00:00Z"),
        price: 2000,
        capacity: 100,
        seatsAvailable: 100,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Marathon Run 2025",
        description: "Annual marathon for fitness lovers.",
        image: "https://picsum.photos/300/200?run",
        category: "Health",
        location: {
          name: "City Stadium",
          address: "Kolkata",
          location: { type: "Point", coordinates: [88.3639, 22.5726] },
        },
        startDate: new Date("2025-10-15T06:00:00Z"),
        price: 300,
        capacity: 2000,
        seatsAvailable: 2000,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Film Screening Night",
        description: "Screening of award-winning indie films.",
        image: "https://picsum.photos/300/200?movie",
        category: "Business",
        location: {
          name: "Film House",
          address: "Goa",
          location: { type: "Point", coordinates: [73.8567, 15.2993] },
        },
        startDate: new Date("2025-11-12T19:00:00Z"),
        price: 150,
        capacity: 120,
        seatsAvailable: 120,
        status: "open",
        organizer: organizerId,
      },

      // -------- Remaining events (mapped to 5 categories) --------

      {
        title: "Dance Workshop",
        description: "Learn urban and hip-hop dance.",
        image: "https://picsum.photos/300/200?dance",
        category: "Music",
        location: {
          name: "Rhythm Studio",
          address: "Pune",
          location: { type: "Point", coordinates: [73.84, 18.51] },
        },
        startDate: new Date("2025-05-03T14:00:00Z"),
        price: 499,
        capacity: 80,
        seatsAvailable: 80,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Hackathon 48 Hours",
        description: "Build innovative tech projects in 48 hours.",
        image: "https://picsum.photos/300/200?hack",
        category: "Tech",
        location: {
          name: "Incubation Center",
          address: "Surat",
          location: { type: "Point", coordinates: [72.83, 21.17] },
        },
        startDate: new Date("2025-05-20T08:00:00Z"),
        endDate: new Date("2025-05-22T08:00:00Z"),
        price: 0,
        capacity: 300,
        seatsAvailable: 300,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Art Exhibition 2025",
        description: "A showcase of modern Indian artists.",
        image: "https://picsum.photos/300/200?art",
        category: "Business",
        location: {
          name: "Art Gallery Hub",
          address: "Delhi",
          location: { type: "Point", coordinates: [77.1, 28.7] },
        },
        startDate: new Date("2025-07-11T10:00:00Z"),
        price: 100,
        capacity: 500,
        seatsAvailable: 500,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Adventure Trek",
        description: "Trekking through scenic mountain routes.",
        image: "https://picsum.photos/300/200?trek",
        category: "Health",
        location: {
          name: "Himalayan Base",
          address: "Manali",
          location: { type: "Point", coordinates: [77.17, 32.24] },
        },
        startDate: new Date("2025-08-20T06:00:00Z"),
        endDate: new Date("2025-08-21T18:00:00Z"),
        price: 800,
        capacity: 50,
        seatsAvailable: 50,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Kids Carnival",
        description: "A fun-filled event for kids and families.",
        image: "https://picsum.photos/300/200?kid",
        category: "Business",
        location: {
          name: "Fun Zone Park",
          address: "Nagpur",
          location: { type: "Point", coordinates: [79.09, 21.14] },
        },
        startDate: new Date("2025-09-15T10:00:00Z"),
        price: 150,
        capacity: 600,
        seatsAvailable: 600,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Wine Tasting Evening",
        description: "Taste premium wines with an expert guide.",
        image: "https://picsum.photos/300/200?wine",
        category: "Food",
        location: {
          name: "Winery Estate",
          address: "Nashik",
          location: { type: "Point", coordinates: [73.76, 19.99] },
        },
        startDate: new Date("2025-10-10T18:00:00Z"),
        price: 700,
        capacity: 120,
        seatsAvailable: 120,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Cultural Festival",
        description: "Celebrate traditional dance, music, and art.",
        image: "https://picsum.photos/300/200?culture",
        category: "Business",
        location: {
          name: "Cultural Ground",
          address: "Jaipur",
          location: { type: "Point", coordinates: [75.79, 26.91] },
        },
        startDate: new Date("2025-11-25T15:00:00Z"),
        price: 200,
        capacity: 1000,
        seatsAvailable: 1000,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Business Expo 2025",
        description: "A large exhibition for businesses & startups.",
        image: "https://picsum.photos/300/200?expo",
        category: "Business",
        location: {
          name: "Expo Hall",
          address: "Indore",
          location: { type: "Point", coordinates: [75.87, 22.72] },
        },
        startDate: new Date("2025-12-05T10:00:00Z"),
        price: 300,
        capacity: 1500,
        seatsAvailable: 1500,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "AI Developer Meetup",
        description: "Meet AI developers & share ideas.",
        image: "https://picsum.photos/300/200?ai",
        category: "Tech",
        location: {
          name: "AI Center",
          address: "Bhopal",
          location: { type: "Point", coordinates: [77.4, 23.25] },
        },
        startDate: new Date("2025-12-22T16:00:00Z"),
        price: 50,
        capacity: 200,
        seatsAvailable: 200,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Book Fair",
        description: "India’s largest book fair.",
        image: "https://picsum.photos/300/200?books",
        category: "Tech",
        location: {
          name: "Book Square Ground",
          address: "Lucknow",
          location: { type: "Point", coordinates: [80.94, 26.84] },
        },
        startDate: new Date("2025-01-15T10:00:00Z"),
        price: 20,
        capacity: 5000,
        seatsAvailable: 5000,
        status: "open",
        organizer: organizerId,
      },
      {
        title: "Garden Flower Show",
        description: "Seasonal display of flowers and plants.",
        image: "https://picsum.photos/300/200?flowers",
        category: "Health",
        location: {
          name: "Botanical Garden",
          address: "Mysuru",
          location: { type: "Point", coordinates: [76.64, 12.3] },
        },
        startDate: new Date("2025-02-05T09:00:00Z"),
        price: 100,
        capacity: 700,
        seatsAvailable: 700,
        status: "open",
        organizer: organizerId,
      },
    ];

    await Event.insertMany(events);
    console.log("20 Events Seeded Successfully!");

    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seedEvents();
